### ISSUE TITLE
include specific components from other yamls?

### ISSUE THREAD

**Issue by havok2063** [tanbro/pyyaml-include#21]
Does this package let me include specific components from other yamls?  For cases where I don't want to include the entire content of the yaml file.  E.g something like

a.yaml
``` 
param:
  - name: A
    type: A1
  - name: B
    type: B1

stuff: 123
```

b.yaml
```
other:
   - param: !include a.yaml/param[0]
  
stuff: !include a.yaml/stuff
```

such that reading in `b.yaml` would result in
```
{
 "other": [{"param": {"name": 'A', "type": 'A1'}}]
 "stuff": 123 
}
```
