### ISSUE TITLE
Wildcard with Hash/Dict/Map

### ISSUE THREAD

**Issue by jose-pr** [tanbro/pyyaml-include#30]
More of a question, but also a request if it is possible. Can i include wildcard and instead of a list fill a object with filename (with/without suffix) as the key and loaded value as the value?
```yaml
files: !include {path_name: include.d/*.yml, map: full_name/without_prefix/custom_function}
```
```yaml
files: !include {path_name: include.d/*.yml, map: without_prefix}
```
This should be:
```yaml
files:
  1:
    name: 1
 2:
    name: 2
```
```yaml
files: !include {path_name: include.d/*.yml, map:  true}
```
This should be:
```yaml
files:
  1.yaml:
    name: 1
 2.yaml:
    name: 2
```
```python
def custom_function(file:str, value:any):
  return Path(file).name
```
