### ISSUE TITLE
merging lists?

### ISSUE THREAD

**Issue by airtonix** [tanbro/pyyaml-include#46]
files:

```
0.yml
a/b/c
  1.yml
  2.yml
f/j/k
  4.yml
  5.yml
```

`{1,2,3,4}.yml`
```
name: 1 # or 2,3,4
```

`0.yml`
```yml
title: merged lists

items:
  - <<: !include "a/b/c/*.yml"
  - <<: !include "f/j/k/*.yml"
```

expected output: 

```
title: merged lists

items: 
  - name: 1
  - name: 2
  - name: 3
  - name: 4
```

variations I've tried: 

`0a.yml`
```yml
title: merged lists

x-one: !include &one "a/b/c/*.yml"
x-two: !include &two "f/j/k/*.yml"

items:
  - <<: *one
  - <<: *two
```
